spring:
  application:
    name: dubbo-use-service
  main:
    allow-bean-definition-overriding: true
    web-application-type: none

  # default disable all
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    base-packages: com.feng.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 9090
      server: netty
    registry:
      #   The Spring Cloud Dubbo's registry extension
      address: spring-cloud://localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'
